<a href="https://colab.research.google.com/github/krishnatiwari4919/MLE-case-study-1/blob/main/MLE_Case_Study_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np

df = pd.read_csv('diabetic_data.csv')
df.head()

,encounter_id,patient_nbr,race,gender,age,weight,admission_type_id,discharge_disposition_id,admission_source_id,time_in_hospital,...,citoglipton,insulin,glyburide-metformin,glipizide-metformin,glimepiride-pioglitazone,metformin-rosiglitazone,metformin-pioglitazone,change,diabetesMed,readmitted
0,2278392,8222157,Caucasian,Female,[0-10),?,6.0,25.0,1.0,1.0,...,No,No,No,No,No,No,No,No,No,NO
1,149190,55629189,Caucasian,Female,[10-20),?,1.0,1.0,7.0,3.0,...,No,Up,No,No,No,No,No,Ch,Yes,>30
2,64410,86047875,AfricanAmerican,Female,[20-30),?,1.0,1.0,7.0,2.0,...,No,No,No,No,No,No,No,No,Yes,NO
3,500364,82442376,Caucasian,Male,[30-40),?,1.0,1.0,7.0,2.0,...,No,Up,No,No,No,No,No,Ch,Yes,NO
4,16680,42519267,Caucasian,Male,[40-50),?,1.0,1.0,7.0,1.0,...,No,Steady,No,No,No,No,No,Ch,Yes,NO

In [2]:
df.isnull().sum()

encounter_id                    0
patient_nbr                     0
race                            0
gender                          0
age                             1
weight                          1
admission_type_id               1
discharge_disposition_id        1
admission_source_id             1
time_in_hospital                1
payer_code                      1
medical_specialty               1
num_lab_procedures              1
num_procedures                  1
num_medications                 1
number_outpatient               1
number_emergency                1
number_inpatient                1
diag_1                          1
diag_2                          1
diag_3                          1
number_diagnoses                1
max_glu_serum               61493
A1Cresult                   56134
metformin                       1
repaglinide                     1
nateglinide                     1
chlorpropamide                  1
glimepiride                     1
acetohexamide                   1
glipizide                       1
glyburide                       1
tolbutamide                     1
pioglitazone                    1
rosiglitazone                   1
acarbose                        1
miglitol                        1
troglitazone                    1
tolazamide                      1
examide                         1
citoglipton                     1
insulin                         1
glyburide-metformin             1
glipizide-metformin             1
glimepiride-pioglitazone        1
metformin-rosiglitazone         1
metformin-pioglitazone          1
change                          1
diabetesMed                     1
readmitted                      1
dtype: int64

In [3]:
df['readmitted_30'] = (df['readmitted'] == '<30').astype(int)
cols_to_drop = [
    'encounter_id', 'patient_nbr', 'weight', 'payer_code', 'admission_type_id',
    'discharge_disposition_id', 'admission_source_id', 'medical_specialty',
    'diag_1', 'diag_2', 'diag_3', 'max_glu_serum', 'A1Cresult'
]
df = df.drop(columns = cols_to_drop)
df.head()

,race,gender,age,time_in_hospital,num_lab_procedures,num_procedures,num_medications,number_outpatient,number_emergency,number_inpatient,...,insulin,glyburide-metformin,glipizide-metformin,glimepiride-pioglitazone,metformin-rosiglitazone,metformin-pioglitazone,change,diabetesMed,readmitted,readmitted_30
0,Caucasian,Female,[0-10),1.0,41.0,0.0,1.0,0.0,0.0,0.0,...,No,No,No,No,No,No,No,No,NO,0
1,Caucasian,Female,[10-20),3.0,59.0,0.0,18.0,0.0,0.0,0.0,...,Up,No,No,No,No,No,Ch,Yes,>30,0
2,AfricanAmerican,Female,[20-30),2.0,11.0,5.0,13.0,2.0,0.0,1.0,...,No,No,No,No,No,No,No,Yes,NO,0
3,Caucasian,Male,[30-40),2.0,44.0,1.0,16.0,0.0,0.0,0.0,...,Up,No,No,No,No,No,Ch,Yes,NO,0
4,Caucasian,Male,[40-50),1.0,51.0,0.0,8.0,0.0,0.0,0.0,...,Steady,No,No,No,No,No,Ch,Yes,NO,0

In [4]:
df.drop(columns = 'readmitted')

,race,gender,age,time_in_hospital,num_lab_procedures,num_procedures,num_medications,number_outpatient,number_emergency,number_inpatient,...,citoglipton,insulin,glyburide-metformin,glipizide-metformin,glimepiride-pioglitazone,metformin-rosiglitazone,metformin-pioglitazone,change,diabetesMed,readmitted_30
0,Caucasian,Female,[0-10),1.0,41.0,0.0,1.0,0.0,0.0,0.0,...,No,No,No,No,No,No,No,No,No,0
1,Caucasian,Female,[10-20),3.0,59.0,0.0,18.0,0.0,0.0,0.0,...,No,Up,No,No,No,No,No,Ch,Yes,0
2,AfricanAmerican,Female,[20-30),2.0,11.0,5.0,13.0,2.0,0.0,1.0,...,No,No,No,No,No,No,No,No,Yes,0
3,Caucasian,Male,[30-40),2.0,44.0,1.0,16.0,0.0,0.0,0.0,...,No,Up,No,No,No,No,No,Ch,Yes,0
4,Caucasian,Male,[40-50),1.0,51.0,0.0,8.0,0.0,0.0,0.0,...,No,Steady,No,No,No,No,No,Ch,Yes,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
66342,AfricanAmerican,Male,[20-30),6.0,27.0,1.0,16.0,0.0,0.0,0.0,...,No,Down,No,No,No,No,No,Ch,Yes,0
66343,Caucasian,Female,[90-100),6.0,84.0,0.0,21.0,3.0,0.0,1.0,...,No,Up,No,No,No,No,No,Ch,Yes,1
66344,Caucasian,Male,[70-80),2.0,38.0,1.0,10.0,0.0,0.0,1.0,...,No,Steady,No,No,No,No,No,No,Yes,0
66345,Caucasian,Male,[60-70),7.0,57.0,0.0,14.0,0.0,0.0,1.0,...,No,Down,No,No,No,No,No,Ch,Yes,0
66346,Caucasian,Femal,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0

In [5]:
df = df.dropna()
df.head()

,race,gender,age,time_in_hospital,num_lab_procedures,num_procedures,num_medications,number_outpatient,number_emergency,number_inpatient,...,insulin,glyburide-metformin,glipizide-metformin,glimepiride-pioglitazone,metformin-rosiglitazone,metformin-pioglitazone,change,diabetesMed,readmitted,readmitted_30
0,Caucasian,Female,[0-10),1.0,41.0,0.0,1.0,0.0,0.0,0.0,...,No,No,No,No,No,No,No,No,NO,0
1,Caucasian,Female,[10-20),3.0,59.0,0.0,18.0,0.0,0.0,0.0,...,Up,No,No,No,No,No,Ch,Yes,>30,0
2,AfricanAmerican,Female,[20-30),2.0,11.0,5.0,13.0,2.0,0.0,1.0,...,No,No,No,No,No,No,No,Yes,NO,0
3,Caucasian,Male,[30-40),2.0,44.0,1.0,16.0,0.0,0.0,0.0,...,Up,No,No,No,No,No,Ch,Yes,NO,0
4,Caucasian,Male,[40-50),1.0,51.0,0.0,8.0,0.0,0.0,0.0,...,Steady,No,No,No,No,No,Ch,Yes,NO,0

In [6]:
from sklearn.model_selection import train_test_split
X = df.drop(['readmitted_30', 'readmitted'], axis = 1)
y = df['readmitted_30']
X = pd.get_dummies(X, drop_first = True)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 42)

In [7]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

In [8]:
from sklearn.linear_model import LogisticRegression
log_reg = LogisticRegression(penalty = 'l2', C= 1.0)
log_reg = log_reg.fit(X_train_scaled, y_train)

In [9]:
from sklearn.metrics import roc_auc_score, classification_report
y_pred_proba = log_reg.predict_proba(X_test_scaled)[:, 1]
y_pred = log_reg.predict(X_test_scaled)
print(roc_auc_score(y_test, y_pred_proba))
print(classification_report(y_test, y_pred))

0.6332127031131657
              precision    recall  f1-score   support

           0       0.88      1.00      0.94     11698
           1       0.42      0.01      0.02      1572

    accuracy                           0.88     13270
   macro avg       0.65      0.50      0.48     13270
weighted avg       0.83      0.88      0.83     13270

In [10]:
submission = pd.DataFrame({
    'Row_ID': X_test.index,
    'Readmission_Probability': y_pred_proba
})
submission.to_csv('readmission_answers.csv', index=False)
print("Success! 'readmission_answers.csv' is ready to upload.")

Success! 'readmission_answers.csv' is ready to upload.